name: build check ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-unit-tests:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Move to the parent directory and fetch dependencies
      - name: Fetch dependencies
        run: |
          cd ..
          git clone https://github.com/razterizer/Core.git

      # Step 3: Change to the correct directory and build
      - name: Build
        run: |
          cd Tests
          ./build_unit_tests.sh
        continue-on-error: false # Ensure errors are not bypassed

  run-unit-tests:
    needs: build-unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: ls
